OWNER_NUMBER=2349131021928
BOT_NAME=PIXEL-MD
OWNER_NAME=Dᴏɴᴡɪᴢ
PACK_NAME=Pixel-md 
AUTHOR=Pixel md•Donwiz 
PREFIX=.
TIME_ZONE=Africa/Lagos
SYMBOL=✎
MENU_TYPE=v3
ONLYPC_MSG=Bot set to work directly in group chat to reduce spam use in private chat
ONLYGC_MSG=Bot set to work directly in private chat to reduce spam use in group
GOODBYE=false
WELCOME=false
WARN=3
SESSION_ID= 
THUMB_IMAGE=https://files.catbox.moe/8fyknb.jpg
FOOTER= ©𝓢𝓾𝓬𝓮𝓼𝓼 𝓫𝔂 𝓟𝓲𝔁𝓮𝓵 𝔀𝓪 𝓫𝓸𝓽
START_MSG=false
